version: '2.1'

services:
  nodejs-template:
    image: nodejs-template
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    # volumes:
    #   - ./src:/usr/src/app/src
    #   - ./server.js:/usr/src/app/server.js
    command: npm run dev